/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { IsString, ValidateNested, IsOptional } from "class-validator";
import { ExercisePlanWhereUniqueInput } from "../../exercisePlan/base/ExercisePlanWhereUniqueInput";
import { Type } from "class-transformer";
import { MealPlanWhereUniqueInput } from "../../mealPlan/base/MealPlanWhereUniqueInput";
import { IsJSONValue } from "../../validators";
import { GraphQLJSON } from "graphql-type-json";
import { InputJsonValue } from "../../types";

@InputType()
class UserCreateInput {
  @ApiProperty({
    required: true,
    type: String,
  })
  @IsString()
  @Field(() => String)
  email!: string;

  @ApiProperty({
    required: false,
    type: () => ExercisePlanWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => ExercisePlanWhereUniqueInput)
  @IsOptional()
  @Field(() => ExercisePlanWhereUniqueInput, {
    nullable: true,
  })
  exercisePlans?: ExercisePlanWhereUniqueInput | null;

  @ApiProperty({
    required: true,
    type: String,
  })
  @IsString()
  @Field(() => String)
  firstName!: string;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  lastName?: string | null;

  @ApiProperty({
    required: false,
    type: () => MealPlanWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => MealPlanWhereUniqueInput)
  @IsOptional()
  @Field(() => MealPlanWhereUniqueInput, {
    nullable: true,
  })
  mealPlan?: MealPlanWhereUniqueInput | null;

  @ApiProperty({
    required: true,
    type: String,
  })
  @IsString()
  @Field(() => String)
  password!: string;

  @ApiProperty({
    required: true,
  })
  @IsJSONValue()
  @Field(() => GraphQLJSON)
  roles!: InputJsonValue;

  @ApiProperty({
    required: true,
    type: String,
  })
  @IsString()
  @Field(() => String)
  username!: string;
}

export { UserCreateInput as UserCreateInput };
