/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import * as nestAccessControl from "nest-access-control";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as common from "@nestjs/common";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { ExercisePlan } from "./ExercisePlan";
import { ExercisePlanCountArgs } from "./ExercisePlanCountArgs";
import { ExercisePlanFindManyArgs } from "./ExercisePlanFindManyArgs";
import { ExercisePlanFindUniqueArgs } from "./ExercisePlanFindUniqueArgs";
import { CreateExercisePlanArgs } from "./CreateExercisePlanArgs";
import { UpdateExercisePlanArgs } from "./UpdateExercisePlanArgs";
import { DeleteExercisePlanArgs } from "./DeleteExercisePlanArgs";
import { ExerciseSetFindManyArgs } from "../../exerciseSet/base/ExerciseSetFindManyArgs";
import { ExerciseSet } from "../../exerciseSet/base/ExerciseSet";
import { User } from "../../user/base/User";
import { ExercisePlanService } from "../exercisePlan.service";
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
@graphql.Resolver(() => ExercisePlan)
export class ExercisePlanResolverBase {
  constructor(
    protected readonly service: ExercisePlanService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "ExercisePlan",
    action: "read",
    possession: "any",
  })
  async _exercisePlansMeta(
    @graphql.Args() args: ExercisePlanCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => [ExercisePlan])
  @nestAccessControl.UseRoles({
    resource: "ExercisePlan",
    action: "read",
    possession: "any",
  })
  async exercisePlans(
    @graphql.Args() args: ExercisePlanFindManyArgs
  ): Promise<ExercisePlan[]> {
    return this.service.exercisePlans(args);
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => ExercisePlan, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "ExercisePlan",
    action: "read",
    possession: "own",
  })
  async exercisePlan(
    @graphql.Args() args: ExercisePlanFindUniqueArgs
  ): Promise<ExercisePlan | null> {
    const result = await this.service.exercisePlan(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => ExercisePlan)
  @nestAccessControl.UseRoles({
    resource: "ExercisePlan",
    action: "create",
    possession: "any",
  })
  async createExercisePlan(
    @graphql.Args() args: CreateExercisePlanArgs
  ): Promise<ExercisePlan> {
    return await this.service.createExercisePlan({
      ...args,
      data: {
        ...args.data,

        user: args.data.user
          ? {
              connect: args.data.user,
            }
          : undefined,
      },
    });
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => ExercisePlan)
  @nestAccessControl.UseRoles({
    resource: "ExercisePlan",
    action: "update",
    possession: "any",
  })
  async updateExercisePlan(
    @graphql.Args() args: UpdateExercisePlanArgs
  ): Promise<ExercisePlan | null> {
    try {
      return await this.service.updateExercisePlan({
        ...args,
        data: {
          ...args.data,

          user: args.data.user
            ? {
                connect: args.data.user,
              }
            : undefined,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => ExercisePlan)
  @nestAccessControl.UseRoles({
    resource: "ExercisePlan",
    action: "delete",
    possession: "any",
  })
  async deleteExercisePlan(
    @graphql.Args() args: DeleteExercisePlanArgs
  ): Promise<ExercisePlan | null> {
    try {
      return await this.service.deleteExercisePlan(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.ResolveField(() => [ExerciseSet], { name: "exerciseSet" })
  @nestAccessControl.UseRoles({
    resource: "ExerciseSet",
    action: "read",
    possession: "any",
  })
  async findExerciseSet(
    @graphql.Parent() parent: ExercisePlan,
    @graphql.Args() args: ExerciseSetFindManyArgs
  ): Promise<ExerciseSet[]> {
    const results = await this.service.findExerciseSet(parent.id, args);

    if (!results) {
      return [];
    }

    return results;
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.ResolveField(() => User, {
    nullable: true,
    name: "user",
  })
  @nestAccessControl.UseRoles({
    resource: "User",
    action: "read",
    possession: "any",
  })
  async getUser(@graphql.Parent() parent: ExercisePlan): Promise<User | null> {
    const result = await this.service.getUser(parent.id);

    if (!result) {
      return null;
    }
    return result;
  }
}
