/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { PrismaService } from "../../prisma/prisma.service";

import {
  Prisma,
  ExerciseSet, // @ts-ignore
  ExerciseSerie, // @ts-ignore
  ExercisePlan,
} from "@prisma/client";

export class ExerciseSetServiceBase {
  constructor(protected readonly prisma: PrismaService) {}

  async count<T extends Prisma.ExerciseSetCountArgs>(
    args: Prisma.SelectSubset<T, Prisma.ExerciseSetCountArgs>
  ): Promise<number> {
    return this.prisma.exerciseSet.count(args);
  }

  async exerciseSets<T extends Prisma.ExerciseSetFindManyArgs>(
    args: Prisma.SelectSubset<T, Prisma.ExerciseSetFindManyArgs>
  ): Promise<ExerciseSet[]> {
    return this.prisma.exerciseSet.findMany(args);
  }
  async exerciseSet<T extends Prisma.ExerciseSetFindUniqueArgs>(
    args: Prisma.SelectSubset<T, Prisma.ExerciseSetFindUniqueArgs>
  ): Promise<ExerciseSet | null> {
    return this.prisma.exerciseSet.findUnique(args);
  }
  async createExerciseSet<T extends Prisma.ExerciseSetCreateArgs>(
    args: Prisma.SelectSubset<T, Prisma.ExerciseSetCreateArgs>
  ): Promise<ExerciseSet> {
    return this.prisma.exerciseSet.create<T>(args);
  }
  async updateExerciseSet<T extends Prisma.ExerciseSetUpdateArgs>(
    args: Prisma.SelectSubset<T, Prisma.ExerciseSetUpdateArgs>
  ): Promise<ExerciseSet> {
    return this.prisma.exerciseSet.update<T>(args);
  }
  async deleteExerciseSet<T extends Prisma.ExerciseSetDeleteArgs>(
    args: Prisma.SelectSubset<T, Prisma.ExerciseSetDeleteArgs>
  ): Promise<ExerciseSet> {
    return this.prisma.exerciseSet.delete(args);
  }

  async findExerciseSerie(
    parentId: string,
    args: Prisma.ExerciseSerieFindManyArgs
  ): Promise<ExerciseSerie[]> {
    return this.prisma.exerciseSet
      .findUniqueOrThrow({
        where: { id: parentId },
      })
      .exerciseSerie(args);
  }

  async getExercisePlans(parentId: string): Promise<ExercisePlan | null> {
    return this.prisma.exerciseSet
      .findUnique({
        where: { id: parentId },
      })
      .exercisePlans();
  }
}
