import {
  Entity,
  Column,
  PrimaryGeneratedColumn,
  CreateDateColumn,
  UpdateDateColumn,
  OneToMany,
  ManyToOne,
  JoinColumn,
} from 'typeorm';
import { Workout } from './workout.entity';
import { UserRole } from '../utils/roles.enum';
import { ObjectType, Field, ID } from '@nestjs/graphql';

@ObjectType()
@Entity('users')
export class User {
  @Field(() => ID)
  @PrimaryGeneratedColumn('uuid')
  id: string;

  @Field()
  @Column()
  name: string;

  @Field()
  @Column({ unique: true })
  email: string;

  @Column()
  password: string;

  @Field({ nullable: true })
  @Column({ name: 'phone', nullable: true })
  phone: string;

  @Field()
  @CreateDateColumn({ name: 'created_at' })
  createdAt: Date;

  @Field()
  @UpdateDateColumn({ name: 'updated_at' })
  updatedAt: Date;

  @Field(() => [Workout], { nullable: true })
  @OneToMany(() => Workout, (workout) => workout.user)
  workouts: Workout[];

  @Field()
  @Column({ name: 'is_password_auto_generated', default: false })
  isPasswordAutoGenerated: boolean;

  @Field(() => UserRole)
  @Column({
    name: 'role',
    type: 'enum',
    enum: UserRole,
    default: UserRole.CLIENT,
  })
  role: UserRole;

  @Column({ name: 'trainer_id', nullable: true })
  trainerId: string;

  @Column({ name: 'nutritionist_id', nullable: true })
  nutritionistId: string;

  @ManyToOne(() => User, { nullable: true })
  @JoinColumn({ name: 'trainer_id' })
  trainer: User;

  @ManyToOne(() => User, { nullable: true })
  @JoinColumn({ name: 'nutritionist_id' })
  nutritionist: User;

  @OneToMany(() => User, (user) => user.trainer)
  clients_as_trainer: User[];

  @OneToMany(() => User, (user) => user.nutritionist)
  clients_as_nutritionist: User[];
}
