import { Injectable } from '@nestjs/common';
import { InjectRepository } from '@nestjs/typeorm';
import { Repository } from 'typeorm';
import { User } from '../../entities/user.entity';

@Injectable()
export class UsersRepository {
  constructor(
    @InjectRepository(User)
    private readonly repository: Repository<User>,
  ) {}

  async create(data: Partial<User>): Promise<User> {
    const user = this.repository.create(data);
    return this.repository.save(user);
  }

  async findById(id: string): Promise<User | null> {
    return this.repository.findOneBy({ id });
  }

  async findByEmail(email: string): Promise<User | null> {
    return this.repository.findOne({
      where: { email },
      select: ['id', 'name', 'email', 'password', 'phone', 'role', 'isPasswordAutoGenerated', 'createdAt', 'updatedAt']
    });
  }

  async update(id: string, data: Partial<User>): Promise<User | null> {
    await this.repository.update(id, data);
    return this.findById(id);
  }

  async delete(id: string): Promise<void> {
    await this.repository.delete(id);
  }

  async findAll(): Promise<User[]> {
    return this.repository.find();
  }

  async findClientsForTrainer(trainerId: string): Promise<User[]> {
    return this.repository.find({
      where: { trainer: { id: trainerId } },
      relations: ['workouts'],
    });
  }

  async findClientsForNutritionist(nutritionistId: string): Promise<User[]> {
    return this.repository.find({
      where: { nutritionist: { id: nutritionistId } },
      relations: ['workouts'],
    });
  }

  async findClientById(
    clientId: string,
    professionalId: string,
  ): Promise<User | null> {
    return this.repository.findOne({
      where: [
        { id: clientId, trainer: { id: professionalId } },
        { id: clientId, nutritionist: { id: professionalId } },
      ],
      relations: ['workouts', 'trainer', 'nutritionist'],
    });
  }

  async findProfessionalsByClient(
    clientId: string,
  ): Promise<{ trainer: User | null; nutritionist: User | null }> {
    const client = await this.repository.findOne({
      where: { id: clientId },
      relations: ['trainer', 'nutritionist'],
    });

    return {
      trainer: client?.trainer || null,
      nutritionist: client?.nutritionist || null,
    };
  }

  async findByIdWithRelations(id: string): Promise<User | null> {
    return this.repository.findOne({
      where: { id },
      relations: ['trainer', 'nutritionist'],
    });
  }
}
