/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { PrismaService } from "../../prisma/prisma.service";

import {
  Prisma,
  ExerciseSerie, // @ts-ignore
  ExerciseSet, // @ts-ignore
  Exercise,
} from "@prisma/client";

export class ExerciseSerieServiceBase {
  constructor(protected readonly prisma: PrismaService) {}

  async count<T extends Prisma.ExerciseSerieCountArgs>(
    args: Prisma.SelectSubset<T, Prisma.ExerciseSerieCountArgs>
  ): Promise<number> {
    return this.prisma.exerciseSerie.count(args);
  }

  async exerciseSeries<T extends Prisma.ExerciseSerieFindManyArgs>(
    args: Prisma.SelectSubset<T, Prisma.ExerciseSerieFindManyArgs>
  ): Promise<ExerciseSerie[]> {
    return this.prisma.exerciseSerie.findMany(args);
  }
  async exerciseSerie<T extends Prisma.ExerciseSerieFindUniqueArgs>(
    args: Prisma.SelectSubset<T, Prisma.ExerciseSerieFindUniqueArgs>
  ): Promise<ExerciseSerie | null> {
    return this.prisma.exerciseSerie.findUnique(args);
  }
  async createExerciseSerie<T extends Prisma.ExerciseSerieCreateArgs>(
    args: Prisma.SelectSubset<T, Prisma.ExerciseSerieCreateArgs>
  ): Promise<ExerciseSerie> {
    return this.prisma.exerciseSerie.create<T>(args);
  }
  async updateExerciseSerie<T extends Prisma.ExerciseSerieUpdateArgs>(
    args: Prisma.SelectSubset<T, Prisma.ExerciseSerieUpdateArgs>
  ): Promise<ExerciseSerie> {
    return this.prisma.exerciseSerie.update<T>(args);
  }
  async deleteExerciseSerie<T extends Prisma.ExerciseSerieDeleteArgs>(
    args: Prisma.SelectSubset<T, Prisma.ExerciseSerieDeleteArgs>
  ): Promise<ExerciseSerie> {
    return this.prisma.exerciseSerie.delete(args);
  }

  async findExerciseSets(
    parentId: string,
    args: Prisma.ExerciseSetFindManyArgs
  ): Promise<ExerciseSet[]> {
    return this.prisma.exerciseSerie
      .findUniqueOrThrow({
        where: { id: parentId },
      })
      .exerciseSets(args);
  }

  async getExercise(parentId: string): Promise<Exercise | null> {
    return this.prisma.exerciseSerie
      .findUnique({
        where: { id: parentId },
      })
      .exercise();
  }
}
