/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import * as nestAccessControl from "nest-access-control";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as common from "@nestjs/common";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { ExerciseSerie } from "./ExerciseSerie";
import { ExerciseSerieCountArgs } from "./ExerciseSerieCountArgs";
import { ExerciseSerieFindManyArgs } from "./ExerciseSerieFindManyArgs";
import { ExerciseSerieFindUniqueArgs } from "./ExerciseSerieFindUniqueArgs";
import { CreateExerciseSerieArgs } from "./CreateExerciseSerieArgs";
import { UpdateExerciseSerieArgs } from "./UpdateExerciseSerieArgs";
import { DeleteExerciseSerieArgs } from "./DeleteExerciseSerieArgs";
import { ExerciseSetFindManyArgs } from "../../exerciseSet/base/ExerciseSetFindManyArgs";
import { ExerciseSet } from "../../exerciseSet/base/ExerciseSet";
import { Exercise } from "../../exercise/base/Exercise";
import { ExerciseSerieService } from "../exerciseSerie.service";
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
@graphql.Resolver(() => ExerciseSerie)
export class ExerciseSerieResolverBase {
  constructor(
    protected readonly service: ExerciseSerieService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "ExerciseSerie",
    action: "read",
    possession: "any",
  })
  async _exerciseSeriesMeta(
    @graphql.Args() args: ExerciseSerieCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => [ExerciseSerie])
  @nestAccessControl.UseRoles({
    resource: "ExerciseSerie",
    action: "read",
    possession: "any",
  })
  async exerciseSeries(
    @graphql.Args() args: ExerciseSerieFindManyArgs
  ): Promise<ExerciseSerie[]> {
    return this.service.exerciseSeries(args);
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => ExerciseSerie, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "ExerciseSerie",
    action: "read",
    possession: "own",
  })
  async exerciseSerie(
    @graphql.Args() args: ExerciseSerieFindUniqueArgs
  ): Promise<ExerciseSerie | null> {
    const result = await this.service.exerciseSerie(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => ExerciseSerie)
  @nestAccessControl.UseRoles({
    resource: "ExerciseSerie",
    action: "create",
    possession: "any",
  })
  async createExerciseSerie(
    @graphql.Args() args: CreateExerciseSerieArgs
  ): Promise<ExerciseSerie> {
    return await this.service.createExerciseSerie({
      ...args,
      data: {
        ...args.data,

        exercise: args.data.exercise
          ? {
              connect: args.data.exercise,
            }
          : undefined,
      },
    });
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => ExerciseSerie)
  @nestAccessControl.UseRoles({
    resource: "ExerciseSerie",
    action: "update",
    possession: "any",
  })
  async updateExerciseSerie(
    @graphql.Args() args: UpdateExerciseSerieArgs
  ): Promise<ExerciseSerie | null> {
    try {
      return await this.service.updateExerciseSerie({
        ...args,
        data: {
          ...args.data,

          exercise: args.data.exercise
            ? {
                connect: args.data.exercise,
              }
            : undefined,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => ExerciseSerie)
  @nestAccessControl.UseRoles({
    resource: "ExerciseSerie",
    action: "delete",
    possession: "any",
  })
  async deleteExerciseSerie(
    @graphql.Args() args: DeleteExerciseSerieArgs
  ): Promise<ExerciseSerie | null> {
    try {
      return await this.service.deleteExerciseSerie(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.ResolveField(() => [ExerciseSet], { name: "exerciseSets" })
  @nestAccessControl.UseRoles({
    resource: "ExerciseSet",
    action: "read",
    possession: "any",
  })
  async findExerciseSets(
    @graphql.Parent() parent: ExerciseSerie,
    @graphql.Args() args: ExerciseSetFindManyArgs
  ): Promise<ExerciseSet[]> {
    const results = await this.service.findExerciseSets(parent.id, args);

    if (!results) {
      return [];
    }

    return results;
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.ResolveField(() => Exercise, {
    nullable: true,
    name: "exercise",
  })
  @nestAccessControl.UseRoles({
    resource: "Exercise",
    action: "read",
    possession: "any",
  })
  async getExercise(
    @graphql.Parent() parent: ExerciseSerie
  ): Promise<Exercise | null> {
    const result = await this.service.getExercise(parent.id);

    if (!result) {
      return null;
    }
    return result;
  }
}
